### ISSUE TITLE
kernel panic with h2op_send/h2opd

### ISSUE THREAD

**Issue by jarissimo** [fu-ilab-swp18/pflanzen1#27] opened 2018-06-17 21:42 UTC
I can send a lot of packages. But somehow the deamon (i think) produces a kernel panic when receiving data. In the output below, there is also a thread running that constantly measures and sends humidity...

```
h2od
2018-06-17 23:37:55,380 - INFO # Starting Server. Example usage:
2018-06-17 23:37:55,386 - INFO # printf '\xac\x01\x0c\x00\x12\x34\x4e\x67DATA' | nc -6u ff02::1%tapbr0 44555
2018-06-17 23:37:55,389 - INFO # UDP server running on port 44555.
2018-06-17 23:37:56,191 - INFO # Reading from sensor (hdc1000|SENSE_TEMP)
2018-06-17 23:37:56,192 - INFO # Read humidity:
2018-06-17 23:37:56,194 - INFO # Data:	     25.29°C
2018-06-17 23:37:56,197 - INFO # ff02::110 bytes sent to 
2018-06-17 23:37:56,198 - INFO # send humidity
2018-06-17 23:37:58,830 - INFO # fd9c:5921:b4af:ac01::ff0110 bytes sent to 
2018-06-17 23:37:58,836 - INFO # H2OP packet received.  type: H2OP_DATA_HUMIDITY(0x12)  source: 3e89
2018-06-17 23:37:58,837 - INFO # Humidity: 100
2018-06-17 23:38:01,191 - INFO # Reading from sensor (hdc1000|SENSE_TEMP)
2018-06-17 23:38:01,192 - INFO # Read humidity:
2018-06-17 23:38:01,194 - INFO # Data:	     25.30°C
2018-06-17 23:38:01,197 - INFO # ff02::110 bytes sent to 
2018-06-17 23:38:01,198 - INFO # send humidity
2018-06-17 23:38:03,851 - INFO # 0x4355
2018-06-17 23:38:03,853 - INFO # *** RIOT kernel panic:
2018-06-17 23:38:03,854 - INFO # FAILED ASSERTION.
2018-06-17 23:38:03,855 - INFO # 
2018-06-17 23:38:03,862 - INFO # 	pid | name                 | state    Q | pri | stack  ( used) | base addr  | current     
2018-06-17 23:38:03,870 - INFO # 	  - | isr_stack            | -        - |   - |    512 (  132) | 0x1fffc000 | 0x1fffc1c8
2018-06-17 23:38:03,878 - INFO # 	  1 | idle                 | pending  Q |  15 |    256 (  136) | 0x1fffc52c | 0x1fffc5a4 
2018-06-17 23:38:03,886 - INFO # 	  2 | main                 | pending  Q |   7 |   1536 (  828) | 0x1fffc62c | 0x1fffc8f4 
2018-06-17 23:38:03,894 - INFO # 	  3 | 6lo                  | bl rx    _ |   3 |   1024 (  400) | 0x1ffffb84 | 0x1ffffe6c 
2018-06-17 23:38:03,902 - INFO # 	  4 | ipv6                 | running  Q |   4 |   1024 (  700) | 0x1fffdc38 | 0x1fffdf14 
2018-06-17 23:38:03,910 - INFO # 	  5 | udp                  | pending  Q |   5 |   1024 (  292) | 0x20000350 | 0x2000062c 
2018-06-17 23:38:03,918 - INFO # 	  6 | kw2xrf               | bl rx    _ |   2 |   1024 (  444) | 0x1fffd66c | 0x1fffd96c 
2018-06-17 23:38:03,926 - INFO # 	  7 | sensor_thread        | bl mutex _ |   6 |   1536 (  564) | 0x1fffd06c | 0x1fffd584 
2018-06-17 23:38:03,932 - INFO # 	    | SUM                  |            |     |   7936 ( 3496)
2018-06-17 23:38:03,932 - INFO # 
2018-06-17 23:38:03,933 - INFO # *** halted.
2018-06-17 23:38:03,933 - INFO # 
```

It can have something to do with the addresses, as they can't be printed when the `h2op_send` message is called.

**Comment by jcarrano** [comment] 2018-06-18 08:40
I dont' know if this is the cause, buy by default, `printf` cannot print floating point (i.e. `%f`). It is disabled to save space and you can enable it with `USEMODULE += printf_float`

**Comment by jcarrano** [comment] 2018-06-18 08:42
Also, enable `DEBUG_ASSERT_VERBOSE` to get the origin of the assertion.

**Comment by jarissimo** [comment] 2018-06-18 14:55
With DEBUG_ASSERT_VERBOSE enabled:

2018-06-18 16:50:42,169 - INFO # sys/net/gnrc/network_layer/ipv6/nib/_nib-internal.c:306 => 0x10ad
2018-06-18 16:50:42,172 - INFO # *** RIOT kernel panic:
2018-06-18 16:50:42,172 - INFO # FAILED ASSERTION.
2018-06-18 16:50:42,173 - INFO # 
2018-06-18 16:50:42,180 - INFO # 	pid | name                 | state    Q | pri | stack  ( used) | base addr  | current     
2018-06-18 16:50:42,188 - INFO # 	  - | isr_stack            | -        - |   - |    512 (  132) | 0x1fffc000 | 0x1fffc1c8
2018-06-18 16:50:42,196 - INFO # 	  1 | idle                 | pending  Q |  15 |    256 (  136) | 0x1fffc52c | 0x1fffc5a4 
2018-06-18 16:50:42,204 - INFO # 	  2 | main                 | pending  Q |   7 |   1536 (  860) | 0x1fffc62c | 0x1fffc904 
2018-06-18 16:50:42,213 - INFO # 	  3 | 6lo                  | bl rx    _ |   3 |   1024 (  400) | 0x1ffff584 | 0x1ffff86c 
2018-06-18 16:50:42,220 - INFO # 	  4 | ipv6                 | running  Q |   4 |   1024 (  708) | 0x1fffd638 | 0x1fffd914 
2018-06-18 16:50:42,228 - INFO # 	  5 | udp                  | pending  Q |   5 |   1024 (  292) | 0x1ffffd50 | 0x2000002c 
2018-06-18 16:50:42,236 - INFO # 	  6 | kw2xrf               | bl rx    _ |   2 |   1024 (  444) | 0x1fffd06c | 0x1fffd36c 
2018-06-18 16:50:42,242 - INFO # 	    | SUM                  |            |     |   6400 ( 2972)
2018-06-18 16:50:42,243 - INFO # 
2018-06-18 16:50:42,243 - INFO # *** halted.

**Comment by dingens** [comment] 2018-06-21 00:38
I now managed to set up this iotlab thing. (First thing: the fe80:: addresses do work,  our fd..: ones don't. How could I debug this? `ifconfig` says they are set but pings don't arrive)

Anyway I managed to reproduce this with only pings (the `info` command is not upstream yet, just use the ip printed after reset), so I assume it is a RIOT problem...?
```
m3-99;info
1529541106.624622;m3-99;> info
1529541106.626168;m3-99;Node role:         sensor
1529541106.626361;m3-99;Node ID:           73D7
1529541106.627153;m3-99;IP Address:        fd9c:5921:b4af:ac01::73d7
m3-98;ping6 2 fd9c:5921:b4af:ac01::73d7
1529541135.450239;m3-98;> ping6 2 fd9c:5921:b4af:ac01::73d7
1529541136.449995;m3-98;ping timeout
1529541137.452484;m3-98;sys/net/gnrc/network_layer/ipv6/nib/_nib-internal.c:306 => 0x8000e31
1529541137.452668;m3-98;*** RIOT kernel panic:
1529541137.452794;m3-98;FAILED ASSERTION.
1529541137.452907;m3-98;
1529541137.455606;m3-98;        pid | name                 | state    Q | pri | stack  ( used) | base addr  | current     
1529541137.457500;m3-98;          - | isr_stack            | -        - |   - |    512 (  144) | 0x20000000 | 0x200001c8
1529541137.458664;m3-98;          1 | idle                 | pending  Q |  15 |    256 (  156) | 0x20000530 | 0x200005ac 
1529541137.461406;m3-98;          2 | main                 | pending  Q |   7 |   1536 (  524) | 0x20000630 | 0x20000a34 
1529541137.462509;m3-98;          3 | 6lo                  | bl rx    _ |   3 |   1024 (  392) | 0x2000390c | 0x20003bfc 
1529541137.464679;m3-98;          4 | ipv6                 | running  Q |   4 |   1024 (  708) | 0x200019c0 | 0x20001c9c 
1529541137.466919;m3-98;          5 | udp                  | bl rx    _ |   5 |   1024 (  252) | 0x200040d8 | 0x200043dc 
1529541137.468969;m3-98;          6 | at86rf2xx            | bl rx    _ |   2 |   1024 (  432) | 0x200014b8 | 0x200017bc 
1529541137.470439;m3-98;          7 | h2od_thread          | bl mbox  _ |   6 |   1536 (  412) | 0x20000d2c | 0x200011ec 
1529541137.472646;m3-98;            | SUM                  |            |     |   7936 ( 3020)
1529541137.473347;m3-98;
1529541137.473743;m3-98;*** halted.
1529541137.474139;m3-98;
```

CC @miri64 -- `_nib-internal.c` says you wrote it :)

**Comment by miri64** [comment] 2018-06-24 10:45
Try using `gnrc_ipv6_router_default`. 6LoWPAN hosts [are very reduced and only allow resolution of IPv6 link-local addresses in the neighbor cache](https://tools.ietf.org/html/rfc6775#section-5.6). In fact they don't even have a neighbor cache. They just reverse the process described [here](https://tools.ietf.org/html/rfc4291#page-20). Global addresses are resolved via the FIB to the link-local addresses of the neighbor.

**Closed** 2018-07-08 16:16 UTC
Labels: bug
